version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lifestream-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: kanbagi-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Docker ağında localhost yerine servis adı (db) kullanılır!
      - DB_HOST=db
    depends_on:
      - db

volumes:
  pgdata: